apiVersion: v1
kind: Secret
metadata:
  name: redis
data:
  host: cmVkaXMtMTQ0OTQuYzEudXMtY2VudHJhbDEtMi5nY2UuY2xvdWQucmVkaXNsYWJzLmNvbQ==
  password: eXE1eTR4VVB0cGVFc2owSTh3Y2dMVjg1NXlQM05VYmY=
  port: MTQ0OTQ=
